on:
  push:
    branches:  
      - main 
      - develop
      - feature/*
  pull_request:
    branches:
      - main 
      - develop
      - feature/*

jobs:
  build:
    runs-on: ubuntu-latest
    defaults: 
      run:
        working-directory: roman-number

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        java-version: 8.0.332+9
        distribution: 'temurin'
        cache: 'maven'
      
    - name: Build with Maven
      run: mvn -B install --file pom.xml
      
    - name: Static
      run: mvn verify
      
